export const ROUTES = {
  home: "/",
  browse: "/browse",
  auth: {
    signIn: "/sign-in",
    signUp: "/sign-up",
    dealerInvite: "/dealer-invite",
    forgotPassword: "/forgot-password",
    verifyOtp: "/verify-otp",
    resetPassword: "/reset-password",
  },
  dashboard: {
    home: "/dashboard",
    listCar: "/list-car",
    myListings: "/my-listings",
    messages: "/messages",
    profile: "/profile",
  },
  seller: {
    dashboard: "/seller/dashboard",
    myListings: "/seller/my-listings",
    myListingsDetail: (id: string) => `/seller/my-listings/${id}`,
    listCar: "/seller/list-car",
    messages: "/seller/messages",
    dealerProfile: (id: string) => `/seller/dealer-profile/${id}`,
    profile: "/seller/profile",
    settings: "/seller/settings",
    settingsEditProfile: "/seller/settings/edit-profile",
    settingsChangePassword: "/seller/settings/change-password",
    settingsPaymentMethods: "/seller/settings/payment-methods",
    settingsAddPaymentCard: "/seller/settings/payment-methods/add-card",
  },
  dealer: {
    dashboard: "/dealer/dashboard",
    myOffers: "/dealer/my-offers",
    myOffersActive: (id: string) => `/dealer/my-offers/active/${id}`,
    myOffersUnlockChat: (id: string) => `/dealer/my-offers/unlock-chat/${id}`,
    myOffersPayUnlock: (id: string) => `/dealer/my-offers/pay-unlock/${id}`,
    messages: "/dealer/messages",
    sellerProfile: (id: string) => `/dealer/seller-profile/${id}`,
    biddingSold: (id: string) => `/dealer/bidding-sold/${id}`,
    bidding: (id: string) => `/dealer/bidding/${id}`,
    offerFee: (id: string) => `/dealer/offer-fee/${id}`,
    profile: "/dealer/profile",
    settings: "/dealer/settings",
    settingsEditProfile: "/dealer/settings/edit-profile",
    settingsChangePassword: "/dealer/settings/change-password",
    settingsPaymentMethods: "/dealer/settings/payment-methods",
    settingsAddPaymentCard: "/dealer/settings/payment-methods/add-card",
    dealerProfile: (id: string) => `/dealer/dealer-profile/${id}`,
  },
} as const;
